server {
    listen 80;
    server_name _;
    root /var/www/html;

    location / {
        fastcgi_pass fpm:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/fpm-index.php;
        fastcgi_param SCRIPT_NAME /fpm-index.php;
        include fastcgi_params;
    }
}
